name: Install dependencies
description: "Loads npm cache if existing and installs npm dependencies via `npm ci`."

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache-nodemodules
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - shell: bash
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        npm ci
