name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style:
    name: Code Style (Linting)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install_dependencies

      - name: NPM Linting
        run: npm run lint
